version: '3.3'
services:
  mysqldb:
    image: 'mysql:5.7'
    restart:always
    volumes:
      - 'mydb:/var/lib/mysql'
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
  web:
    build:
      context: .
    ports:
      - '8088:8080'
    volumes:
      - './target/LoginWebApp-1.war:/usr/local/tomcat/webapps/LoginWebApp-1.war'
    depends_on:
      - mysqldb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
